/****************************************************************************/
/* RWS - beta version 0.80                                                  */
/****************************************************************************/

// FPOSRC.H
// Remote Workplace Server - demo program "FPos"

/****************************************************************************/

/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Remote Workplace Server - "FPos" demo program.
 *
 * The Initial Developer of the Original Code is Richard L. Walsh.
 * 
 * Portions created by the Initial Developer are Copyright (C) 2004
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * ***** END LICENSE BLOCK ***** */

/****************************************************************************/

#define IDI_APPICO              1
#define IDI_CHKICO              3
#define IDI_SORTPTR             4
#define IDB_UPBMP               5
#define IDB_DOWNBMP             6

#define IDD_MAIN                100
#define IDC_STATUS              101

#define IDD_WAIT                110

#define IDD_SAVE                120
#define IDD_SAVEEXIT            121
#define IDC_TEXT                122

#define IDD_OPTIONS             140
#define IDC_INTUITIVE           141
#define IDC_LITERAL             142
#define IDC_SORTORDER           143
#define IDC_SORTUP              144
#define IDC_SORTDOWN            145
#define IDC_RESTOREDEF          146
#define IDC_OK                  147
#define IDC_CANCEL              148

/****************************************************************************/

#define IDM_MAIN                200

#define IDM_FILE                210
#define IDM_GETDATA             211
#define IDM_SAVE                212
#define IDM_EXIT                213

#define IDM_SORT                220
#define IDM_SORTDEL             221
#define IDM_SORTNBR             222
#define IDM_SORTVIEW            223
#define IDM_SORTTITLE           224
#define IDM_SORTSIZE            225
#define IDM_SORTKEY             226
#define IDM_SORTPATH            227
#define IDM_SORTDONE            228

#define IDM_SORTFIRST           IDM_SORTDEL

#define IDM_OPTIONS             230
#define IDM_OPTDLG              231
#define IDM_RESETCOL            232

#define IDM_SINGLE              270
#define IDM_OPEN                271
#define IDM_LOCATE              272
#define IDM_MENU                273
#define IDM_DELETE              274

#define IDM_MULTIPLE            280
#define IDM_UNDELETEALL         281
#define IDM_DELETEALL           282

/****************************************************************************/

