/****************************************************************************/
/* RWS - beta version 0.80                                                  */
/****************************************************************************/

// RWSCLS.H
// Remote Workplace Server - Server WPS class "RWSxx" public header

/****************************************************************************/

/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Remote Workplace Server - Server component.
 *
 * The Initial Developer of the Original Code is Richard L. Walsh.
 * 
 * Portions created by the Initial Developer are Copyright (C) 2004-2007
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * ***** END LICENSE BLOCK ***** */

/****************************************************************************/

/*
 * This file was generated by the SOM Compiler.
 * FileName: RWSCLS.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.2
 *     SOM Emitter emith: 2.41
 */

#ifndef SOM_RWS08_h
#define SOM_RWS08_h

#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef RWS08
#define RWS08 SOMObject
#endif
#include <wptrans.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPTransient
    #define M_WPTransient SOMObject
#endif /* M_WPTransient */
#ifndef M_RWS08
    #define M_RWS08 SOMObject
#endif /* M_RWS08 */

/*
 * End of user-defined types.
 */

#define RWS08_MajorVersion 1
#define RWS08_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define RWS08NewClass c
#pragma linkage(c, system)
#define RWS08ClassData d
#define RWS08CClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <RWSCLS.h>
/*--------------Migration------------*/
#define RWS08_classObj RWS08ClassData.classObject
#define _RWS08 RWS08_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK RWS08NewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(RWS08NewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct RWS08ClassDataStructure {
	SOMAny *classObject;
} SOMDLINK RWS08ClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct RWS08CClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK RWS08CClassData;

/*
 * New and Renew macros for RWS08
 */
#define RWS08New() \
   (_somNew(_RWS08 ? _RWS08 : RWS08NewClass(RWS08_MajorVersion, RWS08_MinorVersion)))
#define RWS08Renew(buf) \
   (_somRenew(_RWS08 ? _RWS08 : RWS08NewClass(RWS08_MajorVersion, RWS08_MinorVersion), buf))

/*
 * Override method: somDefaultInit
 */
#define RWS08_somDefaultInit(somSelf,ctrl) \
	SOMObject_somDefaultInit(somSelf,ctrl)

/*
 * Override method: somDestruct
 */
#define RWS08_somDestruct(somSelf,doFree,ctrl) \
	SOMObject_somDestruct(somSelf,doFree,ctrl)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define RWS08_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define RWS08_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define RWS08_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define RWS08_wpAddSettingsPages WPObject_wpAddSettingsPages
#define RWS08_wpAddToObjUseList WPObject_wpAddToObjUseList
#define RWS08_wpAllocMem WPObject_wpAllocMem
#define RWS08_wpAppendObject WPObject_wpAppendObject
#define RWS08_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define RWS08_wpClose WPObject_wpClose
#define RWS08_wpCnrInsertObject WPObject_wpCnrInsertObject
#define RWS08_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define RWS08_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define RWS08_wpConfirmDelete WPObject_wpConfirmDelete
#define RWS08_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define RWS08_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define RWS08_wpCopyObject WPObject_wpCopyObject
#define RWS08_wpCreateAnother WPObject_wpCreateAnother
#define RWS08_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define RWS08_wpCreateShadowObject WPObject_wpCreateShadowObject
#define RWS08_wpDelete WPObject_wpDelete
#define RWS08_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define RWS08_wpDisplayHelp WPObject_wpDisplayHelp
#define RWS08_wpDisplayMenu WPObject_wpDisplayMenu
#define RWS08_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define RWS08_wpDraggedOverObject WPObject_wpDraggedOverObject
#define RWS08_wpDragOver WPObject_wpDragOver
#define RWS08_wpDrop WPObject_wpDrop
#define RWS08_wpDroppedOnObject WPObject_wpDroppedOnObject
#define RWS08_wpEndConversation WPObject_wpEndConversation
#define RWS08_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define RWS08_wpFilterMenu WPObject_wpFilterMenu
#define RWS08_wpFindUseItem WPObject_wpFindUseItem
#define RWS08_wpFormatDragItem WPObject_wpFormatDragItem
#define RWS08_wpFree WPObject_wpFree
#define RWS08_wpFreeMem WPObject_wpFreeMem
#define RWS08_wpHide WPObject_wpHide
#define RWS08_wpInitData WPObject_wpInitData
#define RWS08_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define RWS08_wpInsertMenuItems WPObject_wpInsertMenuItems
#define RWS08_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define RWS08_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define RWS08_wpMenuItemSelected WPObject_wpMenuItemSelected
#define RWS08_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define RWS08_wpModifyMenu WPObject_wpModifyMenu
#define RWS08_wpMoveObject WPObject_wpMoveObject
#define RWS08_wpOpen WPObject_wpOpen
#define RWS08_wpPrintObject WPObject_wpPrintObject
#define RWS08_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define RWS08_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define RWS08_wpQueryConfirmations WPObject_wpQueryConfirmations
#define RWS08_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define RWS08_wpQueryDefaultView WPObject_wpQueryDefaultView
#define RWS08_wpQueryDetailsData WPObject_wpQueryDetailsData
#define RWS08_wpQueryError WPObject_wpQueryError
#define RWS08_wpSetFolder WPObject_wpSetFolder
#define RWS08_wpQueryFolder WPObject_wpQueryFolder
#define RWS08_wpQueryIcon WPObject_wpQueryIcon
#define RWS08_wpQueryIconData WPObject_wpQueryIconData
#define RWS08_wpQueryMinWindow WPObject_wpQueryMinWindow
#define RWS08_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define RWS08_wpQueryStyle WPObject_wpQueryStyle
#define RWS08_wpSetTaskRec WPObject_wpSetTaskRec
#define RWS08_wpFindTaskRec WPObject_wpFindTaskRec
#define RWS08_wpQueryTitle WPObject_wpQueryTitle
#define RWS08_wpRegisterView WPObject_wpRegisterView
#define RWS08_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define RWS08_wpRender WPObject_wpRender
#define RWS08_wpRenderComplete WPObject_wpRenderComplete
#define RWS08_wpReplaceObject WPObject_wpReplaceObject
#define RWS08_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define RWS08_wpRestore WPObject_wpRestore
#define RWS08_wpRestoreData WPObject_wpRestoreData
#define RWS08_wpRestoreLong WPObject_wpRestoreLong
#define RWS08_wpRestoreState WPObject_wpRestoreState
#define RWS08_wpRestoreString WPObject_wpRestoreString
#define RWS08_wpSaveData WPObject_wpSaveData
#define RWS08_wpSaveImmediate WPObject_wpSaveImmediate
#define RWS08_wpSaveDeferred WPObject_wpSaveDeferred
#define RWS08_wpSaveLong WPObject_wpSaveLong
#define RWS08_wpSaveState WPObject_wpSaveState
#define RWS08_wpSaveString WPObject_wpSaveString
#define RWS08_wpScanSetupString WPObject_wpScanSetupString
#define RWS08_wpSetConcurrentView WPObject_wpSetConcurrentView
#define RWS08_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define RWS08_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define RWS08_wpSetDefaultView WPObject_wpSetDefaultView
#define RWS08_wpSetError WPObject_wpSetError
#define RWS08_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define RWS08_wpSetupOnce WPObject_wpSetupOnce
#define RWS08_wpSetIcon WPObject_wpSetIcon
#define RWS08_wpSetIconData WPObject_wpSetIconData
#define RWS08_wpSetMinWindow WPObject_wpSetMinWindow
#define RWS08_wpModifyStyle WPObject_wpModifyStyle
#define RWS08_wpSetTitle WPObject_wpSetTitle
#define RWS08_wpSetup WPObject_wpSetup
#define RWS08_wpSwitchTo WPObject_wpSwitchTo
#define RWS08_wpUnInitData WPObject_wpUnInitData
#define RWS08_wpViewObject WPObject_wpViewObject
#define RWS08_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define RWS08_wpQueryHandle WPObject_wpQueryHandle
#define RWS08_wpUnlockObject WPObject_wpUnlockObject
#define RWS08_wpObjectReady WPObject_wpObjectReady
#define RWS08_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define RWS08_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define RWS08_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define RWS08_wpIsDeleteable WPObject_wpIsDeleteable
#define RWS08_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define RWS08_wpSetObjectID WPObject_wpSetObjectID
#define RWS08_wpQueryObjectID WPObject_wpQueryObjectID
#define RWS08_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define RWS08_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define RWS08_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define RWS08_wpFindViewItem WPObject_wpFindViewItem
#define RWS08_wpLockObject WPObject_wpLockObject
#define RWS08_wpIsLocked WPObject_wpIsLocked
#define RWS08_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define RWS08_wpWaitForClose WPObject_wpWaitForClose
#define RWS08_wpSetMenuStyle WPObject_wpSetMenuStyle
#define RWS08_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define RWS08_wpIdentify WPObject_wpIdentify
#define RWS08_wpSetStyle WPObject_wpSetStyle
#define RWS08_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define RWS08_somDefaultAssign SOMObject_somDefaultAssign
#define RWS08_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define RWS08_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define RWS08_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define RWS08_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define RWS08_somDefaultVAssign SOMObject_somDefaultVAssign
#define RWS08_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define RWS08_somInit SOMObject_somInit
#define RWS08_somFree SOMObject_somFree
#define RWS08_somUninit SOMObject_somUninit
#define RWS08_somGetClass SOMObject_somGetClass
#define RWS08_somGetClassName SOMObject_somGetClassName
#define RWS08_somGetSize SOMObject_somGetSize
#define RWS08_somIsA SOMObject_somIsA
#define RWS08_somIsInstanceOf SOMObject_somIsInstanceOf
#define RWS08_somRespondsTo SOMObject_somRespondsTo
#define RWS08_somDispatch SOMObject_somDispatch
#define RWS08_somClassDispatch SOMObject_somClassDispatch
#define RWS08_somCastObj SOMObject_somCastObj
#define RWS08_somResetObj SOMObject_somResetObj
#define RWS08_somDispatchV SOMObject_somDispatchV
#define RWS08_somDispatchL SOMObject_somDispatchL
#define RWS08_somDispatchA SOMObject_somDispatchA
#define RWS08_somDispatchD SOMObject_somDispatchD
#define RWS08_somPrintSelf SOMObject_somPrintSelf
#define RWS08_somDumpSelf SOMObject_somDumpSelf
#define RWS08_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_RWS08_h */

#ifndef SOM_M_RWS08_h
#define SOM_M_RWS08_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_RWS08
#define M_RWS08 SOMObject
#endif
#include <wptrans.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_RWS08_MajorVersion 1
#define M_RWS08_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_RWS08NewClass c
#pragma linkage(c, system)
#define M_RWS08ClassData d
#define M_RWS08CClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_RWS08_classObj M_RWS08ClassData.classObject
#define _M_RWS08 M_RWS08_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_RWS08NewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_RWS08NewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_RWS08ClassDataStructure {
	SOMAny *classObject;
} SOMDLINK M_RWS08ClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_RWS08CClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_RWS08CClassData;

/*
 * New and Renew macros for M_RWS08
 */
#define M_RWS08New() \
   (_somNew(_M_RWS08 ? _M_RWS08 : M_RWS08NewClass(M_RWS08_MajorVersion, M_RWS08_MinorVersion)))
#define M_RWS08Renew(buf) \
   (_somRenew(_M_RWS08 ? _M_RWS08 : M_RWS08NewClass(M_RWS08_MajorVersion, M_RWS08_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_RWS08_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_RWS08_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_RWS08_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryTitle
 */
#define M_RWS08_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_RWS08_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_RWS08_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_RWS08_wpclsNew M_WPObject_wpclsNew
#define M_RWS08_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_RWS08_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_RWS08_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_RWS08_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_RWS08_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_RWS08_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_RWS08_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_RWS08_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_RWS08_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_RWS08_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_RWS08_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_RWS08_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_RWS08_wpclsSetError M_WPObject_wpclsSetError
#define M_RWS08_wpclsQueryError M_WPObject_wpclsQueryError
#define M_RWS08_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_RWS08_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_RWS08_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_RWS08_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_RWS08_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_RWS08_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_RWS08_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_RWS08_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_RWS08_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_RWS08_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_RWS08_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_RWS08_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_RWS08__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_RWS08__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_RWS08__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_RWS08__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_RWS08_somNew SOMClass_somNew
#define M_RWS08_somNewNoInit SOMClass_somNewNoInit
#define M_RWS08_somRenew SOMClass_somRenew
#define M_RWS08_somRenewNoInit SOMClass_somRenewNoInit
#define M_RWS08_somRenewNoZero SOMClass_somRenewNoZero
#define M_RWS08_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_RWS08_somAllocate SOMClass_somAllocate
#define M_RWS08_somDeallocate SOMClass_somDeallocate
#define M_RWS08__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_RWS08__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_RWS08_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_RWS08_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_RWS08_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_RWS08_somInitClass SOMClass_somInitClass
#define M_RWS08_somInitMIClass SOMClass_somInitMIClass
#define M_RWS08_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_RWS08_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_RWS08_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_RWS08_somClassReady SOMClass_somClassReady
#define M_RWS08_somGetApplyStub SOMClass_somGetApplyStub
#define M_RWS08_somGetClassData SOMClass_somGetClassData
#define M_RWS08_somSetClassData SOMClass_somSetClassData
#define M_RWS08_somGetClassMtab SOMClass_somGetClassMtab
#define M_RWS08_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_RWS08_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_RWS08_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_RWS08_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_RWS08_somGetMemberToken SOMClass_somGetMemberToken
#define M_RWS08_somGetMethodData SOMClass_somGetMethodData
#define M_RWS08_somGetRdStub SOMClass_somGetRdStub
#define M_RWS08_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_RWS08_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_RWS08_somGetMethodToken SOMClass_somGetMethodToken
#define M_RWS08_somGetName SOMClass_somGetName
#define M_RWS08_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_RWS08_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_RWS08_somGetNumMethods SOMClass_somGetNumMethods
#define M_RWS08_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_RWS08_somGetParent SOMClass_somGetParent
#define M_RWS08_somGetParents SOMClass_somGetParents
#define M_RWS08_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_RWS08_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_RWS08_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_RWS08_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_RWS08_somFindMethod SOMClass_somFindMethod
#define M_RWS08_somFindMethodOk SOMClass_somFindMethodOk
#define M_RWS08_somFindSMethod SOMClass_somFindSMethod
#define M_RWS08_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_RWS08_somLookupMethod SOMClass_somLookupMethod
#define M_RWS08_somCheckVersion SOMClass_somCheckVersion
#define M_RWS08_somDescendedFrom SOMClass_somDescendedFrom
#define M_RWS08_somSupportsMethod SOMClass_somSupportsMethod
#define M_RWS08_somDefinedMethod SOMClass_somDefinedMethod
#define M_RWS08_somOverrideMtab SOMClass_somOverrideMtab
#define M_RWS08_somDefaultInit SOMObject_somDefaultInit
#define M_RWS08_somDestruct SOMObject_somDestruct
#define M_RWS08_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_RWS08_somDefaultAssign SOMObject_somDefaultAssign
#define M_RWS08_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_RWS08_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_RWS08_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_RWS08_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_RWS08_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_RWS08_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_RWS08_somInit SOMObject_somInit
#define M_RWS08_somFree SOMObject_somFree
#define M_RWS08_somUninit SOMObject_somUninit
#define M_RWS08_somGetClass SOMObject_somGetClass
#define M_RWS08_somGetClassName SOMObject_somGetClassName
#define M_RWS08_somGetSize SOMObject_somGetSize
#define M_RWS08_somIsA SOMObject_somIsA
#define M_RWS08_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_RWS08_somRespondsTo SOMObject_somRespondsTo
#define M_RWS08_somDispatch SOMObject_somDispatch
#define M_RWS08_somClassDispatch SOMObject_somClassDispatch
#define M_RWS08_somCastObj SOMObject_somCastObj
#define M_RWS08_somResetObj SOMObject_somResetObj
#define M_RWS08_somDispatchV SOMObject_somDispatchV
#define M_RWS08_somDispatchL SOMObject_somDispatchL
#define M_RWS08_somDispatchA SOMObject_somDispatchA
#define M_RWS08_somDispatchD SOMObject_somDispatchD
#define M_RWS08_somPrintSelf SOMObject_somPrintSelf
#define M_RWS08_somDumpSelf SOMObject_somDumpSelf
#define M_RWS08_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_RWS08_h */
